// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cozbuiqfinmfylkqkdns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvemJ1aXFmaW5tZnlsa3FrZG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjU3MTEsImV4cCI6MjA3NDMwMTcxMX0.e6DxYejB3vFSu5JBQhVQ9Du1z-q6G5FMpAkoXI1OHBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});